/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/weather-details` | `/weather-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/disease-detection` | `/disease-detection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pest-detection` | `/pest-detection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pest-map` | `/pest-map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rice-quality` | `/rice-quality`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/weed-detection` | `/weed-detection`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/weather-details` | `/weather-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/disease-detection` | `/disease-detection`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pest-detection` | `/pest-detection`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pest-map` | `/pest-map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rice-quality` | `/rice-quality`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/weed-detection` | `/weed-detection`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/weather-details${`?${string}` | `#${string}` | ''}` | `/weather-details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/disease-detection${`?${string}` | `#${string}` | ''}` | `/disease-detection${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pest-detection${`?${string}` | `#${string}` | ''}` | `/pest-detection${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pest-map${`?${string}` | `#${string}` | ''}` | `/pest-map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rice-quality${`?${string}` | `#${string}` | ''}` | `/rice-quality${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/weed-detection${`?${string}` | `#${string}` | ''}` | `/weed-detection${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/weather-details` | `/weather-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/disease-detection` | `/disease-detection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pest-detection` | `/pest-detection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pest-map` | `/pest-map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rice-quality` | `/rice-quality`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/weed-detection` | `/weed-detection`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
